# Generated by Django 4.2.4 on 2024-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя в Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('enter_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Введенное пользователем имя и фамилия')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('bot_unblocked', models.BooleanField(default=True, verbose_name='Бот разблокирован пользователем')),
                ('is_unblocked', models.BooleanField(default=True, verbose_name='Пользователь разблокирован')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Права администратора')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
